---------------- SCRIPT VARIABLES ----------------

DEFINE EAP_TBLSP          = EAP
DEFINE EAP_TBLSP_PATH     = D:\oracle\product\10.2.0\oradata\eap
DEFINE EAP_TBLSP_SIZE     = 100M
DEFINE EAP_TBLSP_EXTEND   = 10M

DEFINE EAP_LH_TBLSP           = EAP_LOG
DEFINE EAP_LH_TBLSP_PATH      = D:\oracle\product\10.2.0\oradata\eap
DEFINE EAP_LH_TBLSP_SIZE      = 100M
DEFINE EAP_LH_TBLSP_EXTEND    = 10M

DEFINE EAP_IX_TBLSP           = EAP_IDX
DEFINE EAP_IX_TBLSP_PATH      = D:\oracle\product\10.2.0\oradata\eap
DEFINE EAP_IX_TBLSP_SIZE      = 100M
DEFINE EAP_IX_TBLSP_EXTEND    = 10M

DEFINE EAP_SCHEMA         = EAP_ADM
DEFINE EAP_SCHEMA_PWD     = password

DEFINE EAP_USER           = EAP_ALL
DEFINE EAP_USER_PWD       = password


---------------- TABLESPACES ----------------

CREATE TABLESPACE "&EAP_TBLSP"
    LOGGING
    DATAFILE '&EAP_TBLSP_PATH/&EAP_TBLSP..ora' SIZE &EAP_TBLSP_SIZE
    AUTOEXTEND ON NEXT &EAP_TBLSP_EXTEND MAXSIZE UNLIMITED
--  Remove the following line for Oracle8.
    EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE "&EAP_LH_TBLSP"
    LOGGING
    DATAFILE '&EAP_LH_TBLSP_PATH/&EAP_LH_TBLSP..ora' SIZE &EAP_LH_TBLSP_SIZE
    AUTOEXTEND ON NEXT &EAP_LH_TBLSP_EXTEND MAXSIZE UNLIMITED
--  Remove the following line for Oracle8.
    EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO
/

CREATE TABLESPACE "&EAP_IX_TBLSP"
    LOGGING
    DATAFILE '&EAP_IX_TBLSP_PATH/&EAP_IX_TBLSP..ora' SIZE &EAP_IX_TBLSP_SIZE
    AUTOEXTEND ON NEXT &EAP_IX_TBLSP_EXTEND MAXSIZE UNLIMITED
--  Remove the following line for Oracle8.
    EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO
/

---------------- EAP_SCHEMA ----------------

CREATE USER "&EAP_SCHEMA" PROFILE "DEFAULT"
    IDENTIFIED BY "&EAP_SCHEMA_PWD" DEFAULT TABLESPACE "&EAP_TBLSP"
    QUOTA UNLIMITED ON "&EAP_TBLSP"
    QUOTA UNLIMITED ON "&EAP_LH_TBLSP"
    QUOTA UNLIMITED ON "&EAP_IX_TBLSP"
    ACCOUNT UNLOCK
/
GRANT "CONNECT" TO "&EAP_SCHEMA"
/

---------------- EAP TABLES ----------------

CREATE TABLE "&EAP_SCHEMA"."EAP_API"(
    API_ID      CHAR(4)          NOT NULL,
    API_NAME    VARCHAR2(200),
    API_DESC    VARCHAR2(200),
    SORT_NO     NUMBER(38, 0),
    CONSTRAINT PK_API PRIMARY KEY (API_ID)
)TABLESPACE "&EAP_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_AUTH"(
    AUTH_ID      CHAR(4)          NOT NULL,
    AUTH_NAME    VARCHAR2(200),
    AUTH_DESC    VARCHAR2(200),
    SORT_NO      NUMBER(38, 0),
    CONSTRAINT PK_API_1 PRIMARY KEY (AUTH_ID)
)TABLESPACE "&EAP_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_BATCH_LOG"(
    BATCH_DATE       CHAR(8)          NOT NULL,
    STEP_NO          VARCHAR2(4)      NOT NULL,
    SUB_STEP_NO      VARCHAR2(4)      NOT NULL,
    STEP_DESC        VARCHAR2(200),
    PROC_DATETIME    CHAR(14)         NOT NULL
)TABLESPACE "&EAP_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_CARD_ACTIVATE_CODE"(
    ECODE_USER_ID           VARCHAR2(24)     NOT NULL,
    CARD_NUMBER             CHAR(24)         NOT NULL,
    EXPIRE_DATE             CHAR(8)          NOT NULL,
    CARD_TYPE               CHAR(3),
    ACTIVATE_CODE_LENGTH    NUMBER(5, 0),
    ACTIVATE_CODE           VARCHAR2(200),
    CREATE_OPERATOR         CHAR(6),
    CREATE_DATETIME         CHAR(14),
    DELETE_OPERATOR         CHAR(6),
    DELETE_DATETIME         CHAR(14),
    AC_EXPIRE_DATE          CHAR(8),
    CONSTRAINT PK_CARD_ACT_CODE PRIMARY KEY (ECODE_USER_ID, CARD_NUMBER, EXPIRE_DATE)
)TABLESPACE "&EAP_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_CARD_TYPE"(
    CARD_TYPE           CHAR(3)         NOT NULL,
    GID_VERSION         CHAR(2),
    CARD_TYPE_DESC      VARCHAR2(200),
    CARD_TYPE_STATUS    CHAR(1)         NOT NULL,
    EAP_CARD_TYPE       VARCHAR2(10),
    CONSTRAINT PK_CARD_TYPE PRIMARY KEY (CARD_TYPE)
)TABLESPACE "&EAP_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_CHANNEL"(
    CHANNEL_ID         CHAR(2)         NOT NULL,
    CHANNEL_NAME       VARCHAR2(200),
    CHANNEL_DESC       VARCHAR2(200),
    CHANNEL_STATUS     CHAR(1),
    CREATE_OPERATOR    CHAR(6),
    CREATE_DATETIME    CHAR(14),
    MODIFY_OPERATOR    CHAR(6),
    MODIFY_DATETIME    CHAR(14),
    DELETE_OPERATOR    CHAR(6),
    DELETE_DATETIME    CHAR(14),
    UNIT_ID            CHAR(4),
    CONSTRAINT PK_CHANNEL PRIMARY KEY (CHANNEL_ID)
)TABLESPACE "&EAP_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_DEVICE"(
    DEVICE_ID           CHAR(8)         NOT NULL,
    DEVICE_NAME         VARCHAR2(200),
    DEVICE_DESC         VARCHAR2(200),
    DEVICE_STATUS       CHAR(1),
    CHANNEL_ID          CHAR(2),
    DEVICE_TELLER_ID    CHAR(6),
    CREATE_OPERATOR     CHAR(6),
    CREATE_DATETIME     CHAR(14),
    MODIFY_OPERATOR     CHAR(6),
    MODIFY_DATETIME     CHAR(14),
    DELETE_OPERATOR     CHAR(6),
    DELETE_DATETIME     CHAR(14),
    UNIT_ID             CHAR(4),
    CONSTRAINT PK_DEVICE PRIMARY KEY (DEVICE_ID)
)TABLESPACE "&EAP_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_FUTURE_CARDS"(
    CARD_NUMBER           VARCHAR2(24)     NOT NULL,
    DATE_OF_EXPIRATION    CHAR(8)          NOT NULL,
    CARD_TYPE             CHAR(3)          NOT NULL,
    CREATE_DATA           VARCHAR2(500),
    ECODE_USER						VARCHAR2(24)
)TABLESPACE "&EAP_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_ID_CREATOR"(
    CREATOR_ID      VARCHAR2(40),
    CREATOR_VALUE   VARCHAR2(40),
    CREATOR_REMARK  VARCHAR2(200),
    CONSTRAINT PK_ID_CREATOR PRIMARY KEY (CREATOR_ID)
)TABLESPACE "&EAP_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_MENU"(
    MENU_ID      CHAR(4)          NOT NULL,
    MENU_NAME    VARCHAR2(200),
    MENU_TYPE    CHAR(1),
    MENU_LVL     NUMBER(38, 0),
    PARENT_ID    CHAR(4),
    MENU_PATH    VARCHAR2(200),
    SORT_NO      NUMBER(38, 0),
    CONSTRAINT PK_MENU PRIMARY KEY (MENU_ID)
)TABLESPACE "&EAP_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_PRE_USER"
(
    ECODE_USER            VARCHAR2(24)       NOT NULL,
    USER_TYPE             CHAR(2),
    USER_NAME             VARCHAR2(200),
    ID_NO                 VARCHAR2(24),
    ADDRESS               VARCHAR2(200),
    ZIP_CODE              VARCHAR2(6),
    PHONE                 VARCHAR2(20),
    PHONE2                VARCHAR2(20),
    FAX                   VARCHAR2(20),
    EMAIL                 VARCHAR2(50),
    REG_UNIT_NO           VARCHAR2(200),
    UNIT_NO               CHAR(4)            NOT NULL,
    USER_STATUS           CHAR(1)            NOT NULL,
    CREATE_OPERATOR       CHAR(6)            NOT NULL,
    CREATE_DATETIME       CHAR(14)           NOT NULL,
    MODIFY_OPERATOR       CHAR(6),
    MODIFY_DATETIME       CHAR(14),
    DELETE_OPERATOR       CHAR(6),
    DELETE_DATETIME       CHAR(14),
    ACTIVATE_CODE_LENGTH  NUMBER(5,0),
    ACTIVATE_CODE         VARCHAR2(200),
    AC_EXPIRE_DATE        CHAR(8),
    CHANNEL               CHAR(2),
    USER_ID               VARCHAR2(24),
    CARD_TYPE             CHAR(3),
    CARD_NUMBER           VARCHAR2(24),
    EXPIRE_DATE           CHAR(8),
    REAL_ECODE_USER       VARCHAR2(24),
    CONSTRAINT PK_PRE_USER PRIMARY KEY (ECODE_USER)
)TABLESPACE "&EAP_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_ROLE"(
    ROLE_ID            CHAR(4)          NOT NULL,
    ROLE_NAME          VARCHAR2(200),
    ROLE_DESC          VARCHAR2(200),
    ROLE_TYPE          CHAR(1),
    SORT_NO            NUMBER(38, 0),
    CREATE_OPERATOR    CHAR(6)          NOT NULL,
    CREATE_DATETIME    CHAR(14)         NOT NULL,
    MODIFY_OPERATOR    CHAR(6),
    MODIFY_DATETIME    CHAR(14),
    CONSTRAINT PK_ROLE PRIMARY KEY (ROLE_ID)
)TABLESPACE "&EAP_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_ROLE_MENU_API_MAP"(
    ROLE_ID            CHAR(4)     NOT NULL,
    MENU_API_ID        CHAR(4)     NOT NULL,
    MENU_API_TYPE      CHAR(1)     NOT NULL,
    CREATE_OPERATOR    CHAR(6)     NOT NULL,
    CREATE_DATETIME    CHAR(14)    NOT NULL,
    MODIFY_OPERATOR    CHAR(6),
    MODIFY_DATETIME    CHAR(14),
    CONSTRAINT PK_RMA_MAP PRIMARY KEY (ROLE_ID, MENU_API_ID, MENU_API_TYPE)
)TABLESPACE "&EAP_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_TELL_RMA_MAP"(
    TELLER_ID             CHAR(6)     NOT NULL,
    ROLE_MENU_API_ID      CHAR(4)     NOT NULL,
    ROLE_MENU_API_TYPE    CHAR(1)     NOT NULL,
    CREATE_OPERATOR       CHAR(6),
    CREATE_DATETIME       CHAR(14),
    MODIFY_OPERATOR       CHAR(6),
    MODIFY_DATETIME       CHAR(14),
    CONSTRAINT PK_TELL_RMA_MAP PRIMARY KEY (TELLER_ID, ROLE_MENU_API_ID, ROLE_MENU_API_TYPE)
)TABLESPACE "&EAP_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_TELLER"(
    TELLER_ID           CHAR(6)         NOT NULL,
    TELLER_NAME         VARCHAR2(200),
    TELLER_DESC         VARCHAR2(200),
    TELLER_PSW          CHAR(32),
    PSW_FAULTY_LOGIN    NUMBER(2,0),
    UNIT_ID             CHAR(4)         NOT NULL,
    TELLER_TYPE         CHAR(1)         NOT NULL,
    TELLER_STATUS       CHAR(1),
    CREATE_OPERATOR     CHAR(6),
    CREATE_DATETIME     CHAR(14),
    MODIFY_OPERATOR     CHAR(6),
    MODIFY_DATETIME     CHAR(14),
    DELETE_OPERATOR     CHAR(6),
    DELETE_DATETIME     CHAR(14),
    CONSTRAINT PK_TELLER PRIMARY KEY (TELLER_ID)
)TABLESPACE "&EAP_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_TRADE_LOG"(
    TRADE_DATE          CHAR(8)           NOT NULL,
    TRADE_TIME          CHAR(6)           NOT NULL,
    TECCL_DATE          CHAR(8),
    TECCL_TIME          CHAR(6),
    TECCL_SESSION_ID    CHAR(6),
    APP_CODE            CHAR(2)           NOT NULL,
    CHANNEL_CODE        CHAR(2)           NOT NULL,
    UNIT_NO             CHAR(4)           NOT NULL,
    DEVICE_NO           CHAR(8),
    TELLER_ID           CHAR(6),
    SEQ_NO              CHAR(6),
    TRADE_CODE          CHAR(4)           NOT NULL,
    OTP_CARD_TYPE       CHAR(3),
    RETURN_CODE         CHAR(6),
    TRADE_REQUEST       VARCHAR2(2000),
    TRADE_RESPONSE      VARCHAR2(2000)
)TABLESPACE "&EAP_LH_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_TRADE_LOG_HIS"(
    TRADE_DATE          CHAR(8)           NOT NULL,
    TRADE_TIME          CHAR(6)           NOT NULL,
    TECCL_DATE          CHAR(8),
    TECCL_TIME          CHAR(6),
    TECCL_SESSION_ID    CHAR(6),
    APP_CODE            CHAR(2)           NOT NULL,
    CHANNEL_CODE        CHAR(2)           NOT NULL,
    UNIT_NO             CHAR(4)           NOT NULL,
    DEVICE_NO           CHAR(8),
    TELLER_ID           CHAR(6),
    SEQ_NO              CHAR(6),
    TRADE_CODE          CHAR(4)           NOT NULL,
    OTP_CARD_TYPE       CHAR(3),
    RETURN_CODE         CHAR(6),
    TRADE_REQUEST       VARCHAR2(2000),
    TRADE_RESPONSE      VARCHAR2(2000)
)TABLESPACE "&EAP_LH_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_TRADE_LOG_SUM_DAY"(
    UNIT_NO                 CHAR(4)         NOT NULL,
    CARD_TYPE               CHAR(3)         NOT NULL,
    SUM_DATE                CHAR(8)         NOT NULL,
    ASS_CARD_SUM            NUMBER(8, 0),
    BLOCK_CARD_SUM          NUMBER(8, 0),
    REPLACE_CARD_SUM        NUMBER(8, 0),
    LOCK_CARD_SUM           NUMBER(8, 0),
    UNLOCK_CARD_SUM         NUMBER(8, 0),
    ACTIVATE_CARD_SUM       NUMBER(8, 0),
    VERIFY_CODE_SUM         NUMBER(8, 0),
    VERIFY_CODE_SUCC_SUM    NUMBER(8, 0),
    VERIFY_CODE_FAIL_SUM    NUMBER(8, 0),
    CHANNEL_CODE            CHAR(2)         NOT NULL,
    CONSTRAINT PK_TRADE_LOG_SUM_DAY PRIMARY KEY (UNIT_NO, CARD_TYPE, SUM_DATE, CHANNEL_CODE)
)TABLESPACE "&EAP_LH_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_UNIT"(
    UNIT_ID            CHAR(4)         NOT NULL,
    UNIT_NAME          VARCHAR2(200),
    UNIT_DESC          VARCHAR2(200),
    UNIT_STATUS        CHAR(1)         NOT NULL,
    UPPER_UNIT_NO      CHAR(4)         NOT NULL,
    CREATE_OPERATOR    CHAR(6),
    CREATE_DATETIME    CHAR(14),
    MODIFY_OPERATOR    CHAR(6),
    MODIFY_DATETIME    CHAR(14),
    DELETE_OPERATOR    CHAR(6),
    DELETE_DATETIME    CHAR(14),
    CONSTRAINT PK_UNIT PRIMARY KEY (UNIT_ID)
)TABLESPACE "&EAP_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_USER"(
    ECODE_USER         VARCHAR2(24)     NOT NULL,
    USER_TYPE          CHAR(2),
    USER_NAME          VARCHAR2(200),
    ID_NO              VARCHAR2(24),
    ADDRESS            VARCHAR2(200),
    ZIP_CODE           VARCHAR2(6),
    PHONE              VARCHAR2(20),
    PHONE2             VARCHAR2(20),
    FAX                VARCHAR2(20),
    EMAIL              VARCHAR2(50),
    REG_UNIT_NO        VARCHAR2(200),
    UNIT_NO            CHAR(4)          NOT NULL,
    USER_STATUS        CHAR(1)          NOT NULL,
    CREATE_OPERATOR    CHAR(6)          NOT NULL,
    CREATE_DATETIME    CHAR(14)         NOT NULL,
    MODIFY_OPERATOR    CHAR(6),
    MODIFY_DATETIME    CHAR(14),
    DELETE_OPERATOR    CHAR(6),
    DELETE_DATETIME    CHAR(14),
    CONSTRAINT PK_USER PRIMARY KEY (ECODE_USER)
)TABLESPACE "&EAP_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_USER_CHANNEL_MAP"(
    CHANNEL            CHAR(2)         NOT NULL,
    USER_ID            VARCHAR2(24)    NOT NULL,
    ECODE_USER         VARCHAR2(24),
    CHANNEL_STATUS     CHAR(1)         NOT NULL,
    CREATE_OPERATOR    CHAR(6)         NOT NULL,
    CREATE_DATETIME    CHAR(14)        NOT NULL,
    MODIFY_OPERATOR    CHAR(6),
    MODIFY_DATETIME    CHAR(14),
    DELETE_OPERATOR    CHAR(6),
    DELETE_DATETIME    CHAR(14),
    CONSTRAINT PK_U_CHANNEL_MAP PRIMARY KEY (USER_ID, CHANNEL)
)TABLESPACE "&EAP_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_USER_HIS"(
    ECODE_USER         VARCHAR2(24),
    USER_TYPE          CHAR(2),
    USER_NAME          VARCHAR2(200),
    ID_NO              VARCHAR2(24),
    ADDRESS            VARCHAR2(200),
    ZIP_CODE           VARCHAR2(6),
    PHONE              VARCHAR2(20),
    PHONE2             VARCHAR2(20),
    FAX                VARCHAR2(20),
    EMAIL              VARCHAR2(50),
    REG_UNIT_NO        VARCHAR2(200),
    UNIT_NO            CHAR(4)          NOT NULL,
    USER_STATUS        CHAR(1)          NOT NULL,
    CREATE_OPERATOR    CHAR(6)          NOT NULL,
    CREATE_DATETIME    CHAR(14)         NOT NULL,
    MODIFY_OPERATOR    CHAR(6),
    MODIFY_DATETIME    CHAR(14),
    DELETE_OPERATOR    CHAR(6)          NOT NULL,
    DELETE_DATETIME    CHAR(14)         NOT NULL
)TABLESPACE "&EAP_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_USER_PASSWORD"(
    ECODE_USER_ID       VARCHAR2(24)     NOT NULL,
    ECODE_USER_TYPE     CHAR(1)          NOT NULL,
    PASSWORD            CHAR(12),
    SP_FAULTY_LOGIN     NUMBER(38, 0),
    OTP_FAULTY_LOGIN    NUMBER(38, 0),
    STATUS              CHAR(1),
    CONSTRAINT PK_USER_PASSWORD PRIMARY KEY (ECODE_USER_ID)
)TABLESPACE "&EAP_TBLSP";

CREATE TABLE "&EAP_SCHEMA"."EAP_USER_TYPE"(
    USER_TYPE         CHAR(2)         NOT NULL,
    USER_TYPE_DESC    VARCHAR2(200),
    CONSTRAINT PK_USER_TYPE PRIMARY KEY (USER_TYPE)
)TABLESPACE "&EAP_TBLSP";

---------------- INDEXES ----------------

CREATE INDEX "&EAP_SCHEMA"."IDX_RMAM_ROLE_ID" ON "&EAP_SCHEMA"."EAP_ROLE_MENU_API_MAP"(ROLE_ID) TABLESPACE "&EAP_IX_TBLSP";

---------------- USERS AND PERMISSIONS ----------------

CREATE USER "&EAP_USER" PROFILE "DEFAULT" 
    IDENTIFIED BY "&EAP_USER_PWD" DEFAULT TABLESPACE "&EAP_TBLSP" 
    QUOTA UNLIMITED 
    ON "&EAP_TBLSP" 
    ACCOUNT UNLOCK
/
GRANT "CONNECT" TO "&EAP_USER"
/

GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_API"                     TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_AUTH"                    TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_BATCH_LOG"               TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_CARD_ACTIVATE_CODE"      TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_CARD_TYPE"               TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_CHANNEL"                 TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_DEVICE"                  TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_FUTURE_CARDS"            TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_MENU"                    TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_PRE_USER"                TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_ROLE"                    TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_ROLE_MENU_API_MAP"       TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_TELL_RMA_MAP"            TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_TELLER"                  TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_TRADE_LOG"               TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_TRADE_LOG_HIS"           TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_TRADE_LOG_SUM_DAY"       TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_UNIT"                    TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_USER"                    TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_USER_CHANNEL_MAP"        TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_USER_HIS"                TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_USER_PASSWORD"           TO "&EAP_USER";
GRANT DELETE, INSERT, SELECT, UPDATE ON "&EAP_SCHEMA"."EAP_USER_TYPE"               TO "&EAP_USER";
