--
--ER/Studio 6.0 SQL Code Generation
-- Company :      todos
-- Project :      cem-p.dm1
-- Author :       Tiger
--
-- Date Created : Tuesday, July 13, 2010 20:46:06
-- Target DBMS : MySQL 4.x
--


-- 
-- TABLE: COMMANDS_SEND_HIS 
--

CREATE TABLE COMMANDS_SEND_HIS(
    SEND_ID             CHAR(10),
    USER_ID             CHAR(6),
    DEVICE_TYPE_ID      CHAR(6),
    DEVICE_ID           CHAR(6),
    TASK_DEFINE_TIME    CHAR(14)    NOT NULL,
    TASK_PLAN_TIME      CHAR(14)    NOT NULL,
    COMMANDS_TYPE       CHAR(1)     NOT NULL,
    TEMPLATE_ID         CHAR(6),
    STATUS              CHAR(1)     NOT NULL,
    EXEC_BEGIN_TIME     CHAR(14)    NOT NULL,
    EXEC_END_TIME       CHAR(14)    NOT NULL
)
;



-- 
-- TABLE: COMMANDS_SEND_LIST 
--

CREATE TABLE COMMANDS_SEND_LIST(
    SEND_ID             CHAR(10)    NOT NULL,
    USER_ID             CHAR(6),
    DEVICE_TYPE_ID      CHAR(6),
    DEVICE_ID           CHAR(6),
    TASK_DEFINE_TIME    CHAR(14)    NOT NULL,
    TASK_PLAN_TIME      CHAR(14)    NOT NULL,
    COMMANDS_TYPE       CHAR(1)     NOT NULL,
    TEMPLATE_ID         CHAR(6),
    STATUS              CHAR(1)     NOT NULL,
    PRIMARY KEY (SEND_ID)
)
;



-- 
-- TABLE: DEVICE_COLLECT_LOG 
--

CREATE TABLE DEVICE_COLLECT_LOG(
    SEND_ID          CHAR(10)       NOT NULL,
    DEVICE_ID        CHAR(6)        NOT NULL,
    DEVICE_NAME      VARCHAR(60),
    DEVICE_IP        VARCHAR(50),
    USER_ID          CHAR(6)        NOT NULL,
    COLLECT_BEGIN    CHAR(14),
    COLLECT_END      CHAR(14),
    STATUS           CHAR(1),
    LOG_CONT         TEXT
)
;



-- 
-- TABLE: DEVICE_COMMAND_EXEC_LOG 
--

CREATE TABLE DEVICE_COMMAND_EXEC_LOG(
    LOG_ID          CHAR(10)    NOT NULL,
    USER_ID         CHAR(6),
    DEVICE_ID       CHAR(6)     NOT NULL,
    EXEC_BEGIN      CHAR(14),
    EXEC_END        CHAR(14),
    COMMAND_CONT    TEXT,
    PRIMARY KEY (LOG_ID)
)
;



-- 
-- TABLE: DEVICE_INFO 
--

CREATE TABLE DEVICE_INFO(
    DEVICE_ID             CHAR(6)         NOT NULL,
    DEVICE_NAME_EN        VARCHAR(60)     NOT NULL,
    DEVICE_ABB_NAME_EN    VARCHAR(60),
    DEVICE_NAME_CN        VARCHAR(60)     NOT NULL,
    TYPE_ID               CHAR(6),
    LOCATION_ID           CHAR(6),
    DEVICE_STATUS         CHAR(1)         NOT NULL,
    FRONT_HOST_ID         CHAR(6),
    DEVICE_IP             VARCHAR(50)     NOT NULL,
    DEVICE_PORT           VARCHAR(50)     NOT NULL,
    DEVICE_USER           VARCHAR(50)     NOT NULL,
    DEVICE_PASSWORD       VARCHAR(50)     NOT NULL,
    DEVICE_PROMPT         VARCHAR(10)     NOT NULL,
    REMARK                VARCHAR(200),
    PRIMARY KEY (DEVICE_ID)
)
;



-- 
-- TABLE: DEVICE_INSPECT_LOG 
--

CREATE TABLE DEVICE_INSPECT_LOG(
    SEND_ID          CHAR(10)       NOT NULL,
    DEVICE_ID        CHAR(6)        NOT NULL,
    DEVICE_NAME      VARCHAR(60),
    DEVICE_IP        VARCHAR(50),
    USER_ID          CHAR(6)        NOT NULL,
    INSPECT_BEGIN    CHAR(14),
    INSPECT_END      CHAR(14),
    STATUS           CHAR(1),
    LOG_CONT         TEXT
)
;



-- 
-- TABLE: DEVICE_MAINTAIN_LOG 
--

CREATE TABLE DEVICE_MAINTAIN_LOG(
    SEND_ID           CHAR(10)       NOT NULL,
    DEVICE_ID         CHAR(6)        NOT NULL,
    DEVICE_NAME       VARCHAR(60),
    DEVICE_IP         VARCHAR(50),
    USER_ID           CHAR(6)        NOT NULL,
    MAINTAIN_BEGIN    CHAR(14),
    MAINTAIN_END      CHAR(14),
    STATUS            CHAR(1),
    LOG_CONT          TEXT
)
;



-- 
-- TABLE: DEVICE_PORT_INFO 
--

CREATE TABLE DEVICE_PORT_INFO(
    PORT_ID      CHAR(6)         NOT NULL,
    DEVICE_ID    CHAR(6),
    PORT_SN      VARCHAR(60)     NOT NULL,
    TYPE_ID      CHAR(6),
    STATUS       CHAR(1)         NOT NULL,
    REMARK       VARCHAR(200),
    PRIMARY KEY (PORT_ID)
)
;



-- 
-- TABLE: DEVICE_PORT_RXP 
--

CREATE TABLE DEVICE_PORT_RXP(
    SEND_ID        CHAR(10),
    DEVICE_ID      CHAR(6),
    DEVICE_NAME    VARCHAR(60),
    PORT_ID        CHAR(6),
    PORT_SN        VARCHAR(60),
    RXP            DECIMAL(10, 2)
)
;



-- 
-- TABLE: DEVICE_PORT_TYPE 
--

CREATE TABLE DEVICE_PORT_TYPE(
    TYPE_ID            CHAR(6)           NOT NULL,
    TYPE_NAME_EN       VARCHAR(60)       NOT NULL,
    TYPE_NAME_CN       VARCHAR(60),
    STANDARD_RX_MAX    DECIMAL(10, 2),
    STANDARD_RX_MIN    DECIMAL(10, 2),
    NETWORK_RX_MIN     DECIMAL(10, 2),
    REMARK             VARCHAR(200),
    PRIMARY KEY (TYPE_ID)
)
;



-- 
-- TABLE: DEVICE_TYPE 
--

CREATE TABLE DEVICE_TYPE(
    TYPE_ID                 CHAR(6)         NOT NULL,
    TYPE_NAME_EN            VARCHAR(60)     NOT NULL,
    TYPE_NAME_CN            VARCHAR(60)     NOT NULL,
    INSPECT_COMMANDS        TEXT,
    INSPECT_COMMANDS_EXP    VARCHAR(200),
    COLLECT_COMMANDS        TEXT,
    APP_PICTURE             LONGBLOB,
    REMARK                  VARCHAR(200),
    PRIMARY KEY (TYPE_ID)
)
;



-- 
-- TABLE: FRONT_HOST_INFO 
--

CREATE TABLE FRONT_HOST_INFO(
    HOST_ID             CHAR(6)         NOT NULL,
    HOST_NAME_EN        VARCHAR(60)     NOT NULL,
    HOST_ABB_NAME_EN    VARCHAR(60),
    HOST_NAME_CN        VARCHAR(60)     NOT NULL,
    LOCATION_ID         CHAR(6),
    HOST_STATUS         CHAR(1)         NOT NULL,
    HOST_IP             VARCHAR(50)     NOT NULL,
    HOST_PORT           VARCHAR(50)     NOT NULL,
    HOST_USER           VARCHAR(50)     NOT NULL,
    HOST_PASSWORD       VARCHAR(50)     NOT NULL,
    HOST_PROMPT         VARCHAR(200)    NOT NULL,
    REMARK              VARCHAR(200),
    PRIMARY KEY (HOST_ID)
)
;



-- 
-- TABLE: LOCATION_INFO 
--

CREATE TABLE LOCATION_INFO(
    LOCATION_ID         CHAR(6)         NOT NULL,
    LOCATION_NAME_EN    VARCHAR(60)     NOT NULL,
    LOCATION_NAME_CN    VARCHAR(60)     NOT NULL,
    REMARK              VARCHAR(200),
    PRIMARY KEY (LOCATION_ID)
)
;



-- 
-- TABLE: MAINTAIN_COMMANDS_TEMPLATE 
--

CREATE TABLE MAINTAIN_COMMANDS_TEMPLATE(
    TEMP_ID      CHAR(6)         NOT NULL,
    TEMP_NAME    VARCHAR(60)     NOT NULL,
    TEMP_DESC    VARCHAR(200),
    TEMP_CONT    TEXT,
    PRIMARY KEY (TEMP_ID)
)
;



-- 
-- TABLE: MAINTAIN_TEAM 
--

CREATE TABLE MAINTAIN_TEAM(
    TEAM_ID      CHAR(6)         NOT NULL,
    TEAM_NAME    VARCHAR(60)     NOT NULL,
    REMARK       VARCHAR(200),
    PRIMARY KEY (TEAM_ID)
)
;



-- 
-- TABLE: MAINTAIN_TEAM_DEVICE_MAP 
--

CREATE TABLE MAINTAIN_TEAM_DEVICE_MAP(
    MAP_ID       CHAR(6)    NOT NULL,
    TEAM_ID      CHAR(6),
    DEVICE_ID    CHAR(6),
    PRIMARY KEY (MAP_ID)
)
;



-- 
-- TABLE: MAINTAIN_TEAM_USER_MAP 
--

CREATE TABLE MAINTAIN_TEAM_USER_MAP(
    MAP_ID     CHAR(6)    NOT NULL,
    TEAM_ID    CHAR(6),
    USER_ID    CHAR(6)    NOT NULL,
    PRIMARY KEY (MAP_ID)
)
;



-- 
-- TABLE: SYSTEM_OPERATION_LOG 
--

CREATE TABLE SYSTEM_OPERATION_LOG(
    LOG_ID                CHAR(10)        NOT NULL,
    USER_ID               CHAR(6),
    USER_NAME             VARCHAR(60),
    OPERATION_TIME        CHAR(14),
    OPERATION_FUN_ID      VARCHAR(50),
    OPERATION_FUN_NAME    VARCHAR(50),
    RETURN_CODE           VARCHAR(10),
    REMARK                VARCHAR(200),
    PRIMARY KEY (LOG_ID)
)
;



-- 
-- TABLE: DEVICE_INFO 
--

ALTER TABLE DEVICE_INFO ADD CONSTRAINT RefDEVICE_TYPE4 
    FOREIGN KEY (TYPE_ID)
    REFERENCES DEVICE_TYPE(TYPE_ID)
;

ALTER TABLE DEVICE_INFO ADD CONSTRAINT RefLOCATION_INFO5 
    FOREIGN KEY (LOCATION_ID)
    REFERENCES LOCATION_INFO(LOCATION_ID)
;


-- 
-- TABLE: DEVICE_PORT_INFO 
--

ALTER TABLE DEVICE_PORT_INFO ADD CONSTRAINT RefDEVICE_INFO10 
    FOREIGN KEY (DEVICE_ID)
    REFERENCES DEVICE_INFO(DEVICE_ID)
;

ALTER TABLE DEVICE_PORT_INFO ADD CONSTRAINT RefDEVICE_PORT_TYPE11 
    FOREIGN KEY (TYPE_ID)
    REFERENCES DEVICE_PORT_TYPE(TYPE_ID)
;


-- 
-- TABLE: FRONT_HOST_INFO 
--

ALTER TABLE FRONT_HOST_INFO ADD CONSTRAINT RefLOCATION_INFO6 
    FOREIGN KEY (LOCATION_ID)
    REFERENCES LOCATION_INFO(LOCATION_ID)
;


-- 
-- TABLE: MAINTAIN_TEAM_DEVICE_MAP 
--

ALTER TABLE MAINTAIN_TEAM_DEVICE_MAP ADD CONSTRAINT RefMAINTAIN_TEAM8 
    FOREIGN KEY (TEAM_ID)
    REFERENCES MAINTAIN_TEAM(TEAM_ID)
;

ALTER TABLE MAINTAIN_TEAM_DEVICE_MAP ADD CONSTRAINT RefDEVICE_INFO9 
    FOREIGN KEY (DEVICE_ID)
    REFERENCES DEVICE_INFO(DEVICE_ID)
;


-- 
-- TABLE: MAINTAIN_TEAM_USER_MAP 
--

ALTER TABLE MAINTAIN_TEAM_USER_MAP ADD CONSTRAINT RefMAINTAIN_TEAM7 
    FOREIGN KEY (TEAM_ID)
    REFERENCES MAINTAIN_TEAM(TEAM_ID)
;



